# -*- coding: utf-8 -*-
"""Food Traffic Light Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nBHqbbjhu6jRDN-XwS1gYcAj3GQlulF3
"""

# Commented out IPython magic to ensure Python compatibility.
#clone YOLOv5 and 
!git clone https://github.com/ultralytics/yolov5  # clone repo
# %cd yolov5
# %pip install -qr requirements.txt # install dependencies
# %pip install -q roboflow

import torch
import os
from IPython.display import Image, clear_output  # to display images

print(f"Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})")

from roboflow import Roboflow
rf = Roboflow(model_format="yolov5", notebook="ultralytics")

os.environ["DATASET_DIRECTORY"] = "/content/datasets"

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="8O31O2WnkqLVqw1SNqYd")
project = rf.workspace().project("food-traffic-lamp")
dataset = project.version(3).download("yolov5")

!python train.py --img 416 --batch 16 --epochs 25 --data {dataset.location}/data.yaml --weights yolov5l.pt --cache

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir runs

!python detect.py --weights runs/train/exp/weights/best.pt --img 416 --conf 0.1 --source {dataset.location}/test/images

#display inference on ALL test images

import glob
from IPython.display import Image, display

for imageName in glob.glob('/content/yolov5/runs/detect/exp/*.jpg'): #assuming JPG
    display(Image(filename=imageName))
    print("\n")

!pip install plot-utils

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5  # clone repo
# %cd yolov5
# %pip install -r requirements.txt # install dependencies

!python export.py --weights yolov5l.pt --include torchscript onnx

!python /content/yolov5/yolov5/detect.py --weights yolov5l.onnx

!python /content/yolov5/yolov5/val.py --weights yolov5l.onnx

!python export.py --weights yolov5l.pt --include onnx

!python detect.py --weights yolov5l.onnx --dnn  # detect
!python val.py --weights yolov5l.onnx --dnn  # validate